import 'package:flutter/material.dart';

class TermsAndConditionsPage extends StatelessWidget {
  const TermsAndConditionsPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Colors.black),
          onPressed: () => Navigator.of(context).pop(),
        ),
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Center(
                child: Image.asset(
                  'assets/immy_BrainyBear.png',
                  width: 80,
                  height: 80,
                ),
              ),
              const SizedBox(height: 16),
              const Text(
                'Terms and Conditions',
                style: TextStyle(
                  fontSize: 24,
                  fontWeight: FontWeight.bold,
                ),
              ),
              Container(
                height: 4,
                width: 60,
                margin: const EdgeInsets.only(top: 8, bottom: 24),
                decoration: BoxDecoration(
                  color: const Color(0xFF8B5CF6), // purple-600
                  borderRadius: BorderRadius.circular(2),
                ),
              ),
              _buildTermSection(
                '1. Agreement',
                'By accessing or using Immy, the world\'s first AI powered Teddy Bear, you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you may not access the service.',
              ),
              _buildTermSection(
                '2. Service Description',
                'Immy is a cloud-based service. Future Toys processes and retains audio, interactions, and other data in the cloud to provide and improve our services.',
              ),
              _buildTermSection(
                '3. Data Collection and Privacy',
                'Future Toys collects and stores data and interactions to provide the Immy service. This data may be used to improve our AI systems, enhance user experience, and develop new features. All data collection complies with applicable privacy laws, including COPPA in the United States.',
              ),
              _buildTermSection(
                '4. Parental Consent',
                'Immy is designed for family use. By accepting these terms, you confirm that you are a parent or legal guardian providing consent for your child to use the service, or that you are of legal age to enter into this agreement.',
              ),
              _buildTermSection(
                '5. Limitations',
                'Future Toys is not responsible for any content generated by the AI that may be considered inappropriate despite our content filters and safety measures. We continuously work to improve these systems.',
              ),
              _buildTermSection(
                '6. Changes to Terms',
                'Future Toys reserves the right to modify these terms at any time. We will provide notice of significant changes. Your continued use of Immy after such modifications constitutes your acceptance of the updated terms.',
              ),
              const SizedBox(height: 24),
              SizedBox(
                width: double.infinity,
                height: 50,
                child: ElevatedButton(
                  onPressed: () {
                    Navigator.of(context).pop();
                  },
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFF8B5CF6), // purple-600
                    foregroundColor: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(25),
                    ),
                  ),
                  child: const Text(
                    'Back to Accept Terms',
                    style: TextStyle(fontSize: 16),
                  ),
                ),
              ),
              const SizedBox(height: 24),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildTermSection(String title, String content) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 16.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: const TextStyle(
              fontSize: 16,
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 8),
          Text(
            content,
            style: const TextStyle(
              fontSize: 14,
              height: 1.5,
              color: Color(0xFF4B5563), // gray-600
            ),
          ),
        ],
      ),
    );
  }
}

