name: immy_app
description: "A Flutter application for Immy, the AI-powered teddy bear."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  flutter_svg: ^2.0.5
  flutter_icons_null_safety: ^1.1.0
  qr_flutter: ^4.1.0
  http: ^1.3.0
  http_parser: ^4.0.2
  uuid: ^3.0.7
  path_provider: ^2.1.0
  crypto: ^3.0.3  # Added this line for password hashing
  mobile_scanner: ^3.5.5  # Added for QR code scanning
  mysql1: ^0.20.0 #Added for MySQL database connection

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.0
  build_runner: ^2.3.3  # Needed for mockito code generation

flutter:
  uses-material-design: true
  assets:
    - assets/immy_BrainyBear.png
