name: immy_app
description: "A Flutter application for Immy, the AI-powered teddy bear."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.5.3
  flutter_svg: ^2.1.0
  flutter_icons_null_safety: ^1.1.0
  qr_flutter: ^4.1.0
  http: ^1.3.0
  http_parser: ^4.0.2
  uuid: ^4.5.1
  path_provider: ^2.1.0
  crypto: ^3.0.3
  mobile_scanner: ^3.5.2
  mysql1: ^0.20.0
  provider: ^6.0.5
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  url_launcher: ^6.3.1
  flutter_stripe: ^9.6.0
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/immy_BrainyBear.png
